### ISSUE TITLE
Audit pages for typos

### ISSUE THREAD

**Issue by starbelly** [tsloughter/rebar3.org#11]
Most if not all pages have a few typos or grammatical errors from the readme.io export.

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, can you give me an example? From your description I can't find a proper context 😕

**Comment by ferd** [comment]
I think I got a bunch of them when migrating things and fixing links, but as with links I probably missed a few (many).

**Comment by starbelly** [comment]
Yeah, what @ferd said. This was an issue around the initial migration, but basically it's going through every single sentence in the documentation and looking for typos, grammatical errors, and other oddities such as what Fred alluded to.

**Comment by paulo-ferraz-oliveira** [comment]
OK, I'm very confident that there's no typos now (as per my recent pull request), and will look for grammar issues and "other oddities". Soundtrack will be https://www.youtube.com/watch?v=iYYRH4apXDo.
