### ISSUE TITLE
"Search this site..." box (to the right, in rebar3.org/docs/) doesn't seem to work

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [tsloughter/rebar3.org#36]
The box (to the right, in rebar3.org/docs/), as reported in Slack, seems not to work. @tsloughter

**Comment by paulo-ferraz-oliveira** [comment]
This seems to occur for http://rebar3.org/ (front page), too.

**Comment by paulo-ferraz-oliveira** [comment]
Well, now that I look closer I can't seem to do any search :( [i.e. box to the left in /docs doesn't work either].

**Comment by tsloughter** [comment]
Oh weird, I know the search worked at one point...

**Comment by paulo-ferraz-oliveira** [comment]
> Oh weird, I know the search worked at one point...

I do too :)

**Comment by shamis** [comment]
it seems to be working now

**Comment by paulo-ferraz-oliveira** [comment]
@shamis, did you try a couple of times and using different browsers? We had strange undeterministic issues, just this dawn.

Unless, @tsloughter did something, in which case that'd explain it :-)

**Comment by shamis** [comment]
@paulo-ferraz-oliveira I tested it locally (running hugo) and it was working. Also tested on chrome, firefox, edge and ie 11. It failed on IE. Not sure if that is supported

**Comment by paulo-ferraz-oliveira** [comment]
For reference: I didn't test it locally, and used Chrome on a Mac OS. I'm having errors on the Console, so will check if this is a cache issue.

**Comment by paulo-ferraz-oliveira** [comment]
https://code.jquery.com/jquery-3.3.1.min.js is not getting dowloaded, due to net::ERR_CERT_DATE_INVALID.

**Comment by paulo-ferraz-oliveira** [comment]
Since even https://code.jquery.com/jquery-3.5.1.min.js (the latest version) is attached to an invalid-issuer certificate, I don't see this issue going away any time soon. Do re-open if you feel it's worth it.

**Comment by tsloughter** [comment]
We can just copy the jquery js file to the repo and service it up directly, it doesn't need to come from `code.jquery.com`.
