### ISSUE TITLE
Add Windows installation instructions

### ISSUE THREAD

**Issue by pablocostass** [tsloughter/rebar3.org#43]
Recently @lpil tried installing rebar3 on Windows and they had some problems getting it to work on that OS. 

We should add to the _Getting started_ section (probably in the [_Installing from the Rebar3 escript_](https://www.rebar3.org/docs/getting-started/#installing-from-the-rebar3-escript) subsection) some tips or ways of getting a working rebar3 installation on Windows.

I will try to make these changes Soon™ :wink:

**Comment by ferd** [comment]
Sounds good. The windows install is sort of tricky depending on where the person gets all their stuff. I use a set up based on https://adoptingerlang.org/docs/development/setup/#windows and for me it was always a simpler path to bootstrap to get the little rebar3.cmd file going. It's the one that's missing from the website instructions and then you're stuck having to find the escript mechanisms which are no clearly explained.
