### ISSUE TITLE
Publishing Packages. Text in examples seem to have the color white (on a white background)

### ISSUE THREAD

**Issue by NicklasXYZ** [tsloughter/rebar3.org#76]
A lot of the examples in the documentation seem to have the color white (on a white background). It makes it hard to read if you just intent to have a brief look and not copy the examples to an editor.

Example: https://www.rebar3.org/docs/package_management/publishing-packages/

If it is intentional or actually a problem on my side, then I am sorry for creating this issue :)

**Comment by ferd** [comment]
You probably have javascript disabled, which messes with syntax highlighting?

**Comment by NicklasXYZ** [comment]
These are my chromium settings:

![2021-05-21_00-18](https://user-images.githubusercontent.com/18580183/119055977-3180f780-b9ca-11eb-8f27-3aed56150793.png)

This is an error I receive in the console:
![2021-05-21_00-18_1](https://user-images.githubusercontent.com/18580183/119056011-4067aa00-b9ca-11eb-8e9a-6abec882f31e.png)

**Comment by ferd** [comment]
oh you might want to drop the www then and go directly to the root. I don't know why the redirection isn't working

**Comment by NicklasXYZ** [comment]
Ah yeah, then it works!
Now I wonder how I managed to get to that url.
I remember I was redirected from somewhere else.

**Comment by NicklasXYZ** [comment]
It seems like I reached it from here:  https://hex.pm/docs/rebar3_usage

**Comment by ferd** [comment]
https://github.com/hexpm/hexpm/pull/1031 should take care of it
