### ISSUE TITLE
Sidebar TOC should parity production site

### ISSUE THREAD

**Issue by starbelly** [tsloughter/rebar3.org#9]
Currently the side bar TOC is out of order, does not parity the current production site. An example would be Tutorials is at the top of the site right now, but at the bottom in production.

**Comment by ferd** [comment]
We should also look for reorganizing a few things, but yeah, the site order priority was a bit of a better fit.

**Comment by starbelly** [comment]
@ferd yeah, I was going to close this but will leave it open per what you stated. I think @tsloughter and I talked about organizing all the hex stuff into it's own section with a sub-section per command.

**Comment by ferd** [comment]
Done and reorganized to follow a better priority order.
