### ISSUE TITLE
Custom Dep Resources - New API documentation

### ISSUE THREAD

**Issue by MarkoMin** [tsloughter/rebar3.org#98]
download/4 is wrongly documented based on https://github.com/erlang/rebar3/blob/main/src/rebar_resource_v2.erl
The issue is that 3.rd and 4.th argument are swapped in documentation.

Also, I can't miss a chance to ask why are there 2 documentation sites for Rebar3, .org and .io?

**Comment by ferd** [comment]
The .io is deprecated, we wanted to get rid of it, but people still wanted the old discussions there to be available and we couldn't keep only half of it. So the old deprecated site is still there. unfortunately for us google seems to also index it higher than the actual site.

**Comment by MarkoMin** [comment]
Closing because it's fixed (somewhere)
